defmodule YouBet.Questions do
  @questions [
{:architecture, "How many steps does the Eiffel Tower have?", 1_792},
{:architecture, "How many rooms does Buckingham Palace have?", 775},
{:architecture, "How many rivets does the Eiffel Tower have?", 2_500_000},
{:architecutre, "How many points are on the Statue of Liberty's crown?", 7},
{:astronomy, "How many Earths would fit inside Jupiter?", 1300},
{:astronomy, "How many moons does Jupiter have?", 67},
{:astronomy, "How wide, in kilometres, are Saturns Rings?", 282_000},
{:astronomy, "What is the Moon's diameter, in kilometres?", 3_476},
{:astronomy, "How many times larger than Earth is the Sun?", 330_330},
{:astronomy, "How many tons des the sun lose every year?", 360_000_000},
{:astronomy, "What is the diameter of the sun, in kilometres?", 1_390_000},
{:astronomy, "What is the temperature at the center of the Sun, in degrees Celcius?", 15_000_000},
{:biology, "How many muscles do cats have in each ear?", 32},
{:biology, "On average, how many times a day does a cow defecate?", 16},
{:biology, "How many breaths does the average adult take each year?", 8409600},
{:biology, "What percentage of DNA do humans share with slugs?", 70},
{:biology, "How many times does a whale's heart beat per minute?", 9},
{:biology, "How many muscles are in an elephant trunk?", 15_000},
{:biology, "How many eyes does a butterfly have?", 12_000},
{:biology, "How many years did the oldest recorded elephant live?", 82},
{:biology, "What percentage of plant life is found in the ocean?", 85},
{:biology, "How many bones are in a human foot?", 26},
{:biology, "How long are an average human's eyes closed per day due to blinking, in minutes?", 30},
{:biology, "How many hours a day do koalas sleep?", 18},
{:biology, "How long was the longest recorded flight of a chicken, in seconds?", 13},
{:biology, "What is the lifespace of a squirrel, in years?", 9},
{:biology, "How many eggs per year does the average hen lay?", 228},
{:biology, "How many bones does a human head contain?", 22},
{:biology, "How fast can dolphins swim, in kilometres per hour?", 60},
{:biology, "How fast can sharks swim, in kilometres per hour?", 70},
{:biology, "How fast can cheetahs run, in kilometres per hour?", 114},
{:biology, "How fast can a greyhound run, in kilometres per hour?", 67},
{:biology, "How many spikes does the average porcupine have?", 30_000},
{:biology, "What percentage of a banana is water?", 75},
{:biology, "How fast can a honeybee fly, in kilometres per hour?", 24},
{:biology, "How many litres of water can an elephant's trunk hold?", 5},
{:biology, "How many meters of blood vessels does a human body have?", 96_000_000},
{:biology, "How many times does the average human blink per day?", 25_000},
{:biology, "How many sweat glands does one square inch of human skin contain?", 625},
{:biology, "What percentage of an eggs weight is the shell?", 12},
{:biology, "What is the longest time a person has been in a coma, in years?", 37},
{:biology, "What is the farthest distance a shark can sense a drop of blood, in meters?", 4_000},
{:biology, "How many pounds of feces does an average elephant produce every day?", 50},
{:biology, "How many known species of ladybugs are there?", 4_300},
{:biology, "How many times a second does a house fly flap it's wing?", 200},
{:biology, "How many times a second can a woodpecker peck?", 20},
{:biology, "How many known species of insects are there?", 900_000},
{:geography, "How many sheep are in New Zealand?", 70_000_000},
{:geography, "As of 2016, how many cities, municipalities, districts, towns, townships, villages and hamlets does Canada have?", 5_162},
{:geography, "What was the population of Mexico City in 2010?", 8_851_080},
{:geography, "How many time zones does Russia span?", 11},
{:geography, "What percent of Canada is covered with fresh water?", 9},
{:geography, "How many lakes does Canada have?", 561},
{:geography, "How many countries border China?", 14},
{:geography, "How many rivers does Jamaica have?", 120},
{:geography, "How long is The Great Wall of China, in kilometres?", 6_430},
{:geography, "How many countries does Germany border?", 9},
{:geography, "How many bathtubs could Niagara Falls fill every second?", 4_000},
{:history, "How old was Sir Isaac Newton when he discovered the law of gravity?", 23},
{:history, "In what year was the first full length animated film released?", 1937},
{:history, "When was the electric toothbrush invented?", 1939},
{:history, "When was the doorbell invented?", 1831},
{:history, "When was the tea bag invented?", 1908},
{:history, "When was volleyball invented?", 1895},
{:history, "When was the revolving door invented?", 1888},
{:history, "When was the lie detector invented?", 1921},
{:history, "When was the drinking straw invented?", 1886},
{:history, "When was instant coffee invented?", 1901},
{:history, "When was Pez invented?", 1927},
{:history, "When was the elevator invented?", 1850},
{:history, "When was the toothbrush invented?", 1498},
{:history, "When was the corkscrew invented?", 1890},
{:history, "When was the typewriter invented?", 1829},
{:history, "When was the dishwasher invented?", 1889},
{:history, "When was the wristwatch invented?", 1904},
{:meteorology, "On average, how many times does lightning strike Earth every minute?", 6_000},
{:mathematics, "How many digits does the largest prime number known have (as of December 2017)?", 22_338_618},
{:pop_culture, "How many stars are in the Paramount studios logo?", 22},
{:pop_culture, "In how many weeks was the movie Wayne's World filmed?", 2},
{:pop_culture, "What percentage of movies are rated R", 55},
{:records, "How wide, in inches, was the largest recorded snowflake?", 15},
{:records, "How many teddy bears are there in the world's largest teddy bear collection?", 8_026},
{:records, "How much did the world's largest tape ball weigh, in kilograms?", 907},
{:records, "What is the most number of balloons blown up by an individual in one hour?", 910},
{:records, "How many millimeters was the world's longest eyelash?", 124},
{:records, "What is the most number apples bobbed in one minute by an individual?", 37},
{:records, "What's the fastest 100m slackfline walk, in seconds?", 119},
{:records, "How much did the world's largest rubber band ball weigh, in kilograms?", 4_097},
{:society, "How many homicides where committed in Canada in 2016?", 611},
{:society, "What percentage of burglaries are committed by people aged 13-21?", 80},
{:society, "How many eggs does the average American eat per year?", 263},
{:society, "What percentage of all wine is produced in Italy and France?", 40},
{:society, "How many litres of fuel does a Boeing 747 hold?", 216_847},
{:society, "How many trees worth of paper will the average American consume over their lifetime?", 465},
{:society, "What was the average lifespan in the United States in 1900?", 47},
{:sports, "What's the longest winning streak in Major League Baseball?", 26},
{:sports, "How many dimples does the average golf ball have?", 336},
{:sports, "How many stitches are in an average soccer ball?", 642},
{:sports, "How many holes does a Chinese checkerboard have?", 121}
]

  def random do
    {_topic, question, answer} =
      @questions
      |> Enum.random

    {question, answer}
  end
end